CREATE TABLE MQ135 (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CO VARCHAR(10),
    Alcohol VARCHAR(10),
    CO2 VARCHAR(10),
    Toluen VARCHAR(10),
    NH4 VARCHAR(10),
    Aceton VARCHAR(10),
    Air VARCHAR(10),
    usvhr VARCHAR(10),
    Avg1 VARCHAR(10),
    sdCPM VARCHAR(10),
    CPMCount VARCHAR(10),
    SpaceData100 VARCHAR(10),
    SpaceData200 VARCHAR(10),
    lat VARCHAR(10),
    lng VARCHAR(10),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
