CREATE TABLE MQ303A (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Isobutane VARCHAR(5),
    Hydrogen VARCHAR(5),
    Ethanol VARCHAR(5),
    Air VARCHAR(5),
    usvhr VARCHAR(7),
    Avg1 VARCHAR(7),
    sdCPM VARCHAR(7),
    CPMCount VARCHAR(7),
    SpaceData100 VARCHAR(3),
    SpaceData200 VARCHAR(3),
    lat VARCHAR(11),
    lng VARCHAR(11),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
