CREATE TABLE MQ135 (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(3),
    Acetone VARCHAR(3),
    Toluene VARCHAR(3),
    Alcohol VARCHAR(3),
    CO2 VARCHAR(3),
    NH4 VARCHAR(3),
    CO VARCHAR(3),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(12),
    lng VARCHAR(12),
    reading_time TIMESTAMP DEFAULT UTC_TIMESTAMP
);
