CREATE TABLE MQ131 (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(3),
    O3 VARCHAR(3),
    CL2 VARCHAR(3),
    NOx VARCHAR(3),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(12),
    lng VARCHAR(12),
    reading_time TIMESTAMP DEFAULT UTC_TIMESTAMP
);
