CREATE TABLE MQ137 (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(3),
    CO VARCHAR(3),
    Ethanol VARCHAR(3),
    NH3 VARCHAR(3),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(11),
    lng VARCHAR(11),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
