CREATE TABLE MQ131L (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(4),
    O3 VARCHAR(4),
    CL2 VARCHAR(4),
    NOx VARCHAR(4),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(11),
    lng VARCHAR(11),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
