CREATE TABLE MQ306A (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(5),
    Ethanol VARCHAR(4),
    Hydrogen VARCHAR(5),
    Methane VARCHAR(5),
    IsoButane VARCHAR(5),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(11),
    lng VARCHAR(11),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);