CREATE TABLE MQ307A (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    CO VARCHAR(4),
    H2 VARCHAR(4),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(12),
    lng VARCHAR(12),
    reading_time TIMESTAMP DEFAULT UTC_TIMESTAMP
);
