CREATE TABLE MQ8 (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DHT VARCHAR(15),
    SpaceData100 VARCHAR(7),
    Air VARCHAR(5),
    H2 VARCHAR(5),
    Alcohol VARCHAR(5),
    LPG VARCHAR(5),
    CH4 VARCHAR(5),
    CO VARCHAR(5),
    SpaceData200 VARCHAR(7),
    lat VARCHAR(11),
    lng VARCHAR(11),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
