CREATE TABLE CO2 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	DHT VARCHAR(15),
	SpaceData VARCHAR(8),
	TheoCO2 VARCHAR(9),
	PCoef VARCHAR(16),
	CO2 VARCHAR(11),
	CH4 VARCHAR(10),
	C2H5OH VARCHAR(10),
	CO VARCHAR(11),
	lat VARCHAR(12),
	lng VARCHAR(12),
	reading_time TIMESTAMP DEFAULT UTC_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
